name: Deploy Preevy environment
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
permissions:
  id-token: write
  contents: read
  pull-requests: write
concurrency: preevy-${{ github.event.number }}
jobs:
  deploy:
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ fromJson(steps.preevy_up.outputs.urls-map).frontend[3000] }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.PREEVY_SA_KEY }}'

      - uses: livecycle/preevy-up-action@v2.4.0
        id: preevy_up
        with:
          install: gh-release
          profile-url: ${{ vars.PREEVY_PROFILE_URL }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Send build metadata to public API
        env:
          PR_NUMBER: ${{ github.event.number }}
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          ACTOR: ${{ github.actor }}
          FRONTEND_URL: ${{ fromJson(steps.preevy_up.outputs.urls-map).frontend[3000] }}
        run: |
          payload=$(
            jq -n \
              --arg id "preevy-$RUN_ID" \
              --arg repo "$REPO" \
              --arg pr "$PR_NUMBER" \
              --arg sha "$SHA" \
              --arg branch "${{ github.ref_name || github.ref }}" \
              --arg actor "$ACTOR" \
              --arg frontend "$FRONTEND_URL" \
              '{build_id:$id, repo:$repo, pr_number:($pr|tonumber), commit_sha:$sha, branch:$branch, actor:$actor, frontend_url:$frontend, status:"ready"}'
          )

          curl -sS -X POST "https://preevy-preview-manager.vercel.app/api/previews" \
            -H "Content-Type: application/json" \
            -d "$payload"
