name: Teardown Preevy environment
on:
  pull_request:
    types:
      - closed
permissions:
  id-token: write
  contents: read
concurrency: preevy-${{ github.event.number }}
jobs:
  teardown:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.PREEVY_SA_KEY }}'

      - uses: livecycle/preevy-down-action@v1.4.0
        with:
          profile-url: ${{ vars.PREEVY_PROFILE_URL }}
          install: gh-release
          args: '--force'

      - name: Mark preview as down in dashboard
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          payload=$(
            jq -n \
              --arg id "preevy-$RUN_ID" \
              '{build_id:$id, status:"down"}'
          )

          curl -sS -X POST "https://preevy-preview-manager.vercel.app/api/previews" \
            -H "Content-Type: application/json" \
            -d "$payload"
